export const DATA = [
  {
    id: 1,
    phrase_front: "あめ",
    phrase_back: "なめる",
    choices: [
      {
        id: 1,
        character: "お",
        en: "o",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
      {
        id: 2,
        character: "を",
        en: "wo",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
    ],
    character: "wo",
    category_id: 1,
    category: "particles",
    level: "beginner",
    is_index: true,
  },
  {
    id: 2,
    phrase_front: "て",
    phrase_back: "あらう",
    choices: [
      {
        id: 1,
        character: "を",
        en: "wo",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 2,
        character: "お",
        en: "o",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
    ],
    character: "wo",
    category_id: 2,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 3,
    phrase_front: "おばけ",
    phrase_back: "こわい",
    choices: [
      {
        id: 1,
        character: "わ",
        en: "wa",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
      {
        id: 2,
        character: "は",
        en: "ha",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
    ],
    character: "ha",
    category_id: 3,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 4,
    phrase_front: "ばった",
    phrase_back: "むしです",
    choices: [
      {
        id: 1,
        character: "は",
        en: "ha",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
      {
        id: 2,
        character: "わ",
        en: "wa",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
    ],
    character: "ha",
    category_id: 4,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 5,
    choices: [
      {
        id: 1,
        character: "を",
        en: "wo",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 2,
        character: "お",
        en: "o",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
      {
        id: 3,
        character: "いもうと",
        en: "imouto",
        style_height: 200,
        style_width: 50,
        image: "https://i.ibb.co/kxKnG9P/img-imouto.jpg",
      },
      {
        id: 4,
        character: "よぶ",
        en: "yobu",
        style_height: 100,
        style_width: 50,
        image: "https://i.ibb.co/SN8pcw8/img-yobu.jpg",
      },
    ],
    character: "wo",
    category_id: 5,
    category: "particles",
    level: "intermediate",
    is_index: true,
    answer: "imouto wo yobu",
  },
  {
    id: 6,
    choices: [
      {
        id: 1,
        character: "ぼうし",
        en: "boushi",
        style_height: 120,
        style_width: 50,
        image: "https://i.ibb.co/CVYRNfP/img-boushi.jpg",
      },
      {
        id: 2,
        character: "かぶる",
        en: "kaburu",
        style_height: 120,
        style_width: 50,
        image: "https://i.ibb.co/9sZN0b1/img-kaburu.jpg",
      },
      {
        id: 3,
        character: "を",
        en: "wo",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 4,
        character: "お",
        en: "o",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
    ],
    character: "wo",
    category_id: 6,
    category: "particles",
    level: "intermediate",
    is_index: false,
    answer: "boushi wo kaburu",
  },
  {
    id: 7,
    choices: [
      {
        id: 1,
        character: "なつ",
        en: "natu",
        style_height: 100,
        style_width: 50,
        image: "https://i.ibb.co/ts8myMQ/img-natu.jpg",
      },
      {
        id: 2,
        character: "は",
        en: "ha",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
      {
        id: 3,
        character: "あつい",
        en: "atui",
        style_height: 120,
        style_width: 50,
        image: "https://i.ibb.co/bPqRzXW/img-atui.jpg",
      },
      {
        id: 4,
        character: "わ",
        en: "wa",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
    ],
    character: "ha",
    category_id: 7,
    category: "particles",
    level: "intermediate",
    is_index: false,
    answer: "natu ha atui",
  },
  {
    id: 8,
    choices: [
      {
        id: 1,
        character: "くるま",
        en: "kuruma",
        style_height: 120,
        style_width: 50,
        image: "https://i.ibb.co/2M6DcKc/img-kuruma.jpg",
      },
      {
        id: 2,
        character: "わ",
        en: "wa",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
      {
        id: 3,
        character: "はしる",
        en: "hashiru",
        style_height: 120,
        style_width: 50,
        image: "https://i.ibb.co/fr7gNYS/img-hashiru.jpg",
      },
      {
        id: 2,
        character: "は",
        en: "ha",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
    ],
    character: "ha",
    category_id: 8,
    category: "particles",
    level: "intermediate",
    is_index: false,
    answer: "kuruma ha hashiru",
  },
  {
    id: 9,
    category: "particles",
    category_id: 9,
    level: "advanced",
    is_index: true,
    answer: "おかしをたべる",
    sound_resource:
      "https://dl.dropboxusercontent.com/scl/fi/058e25tmspifom94vep3h/okashiwotaberu.m4a?rlkey=yynjlfxfoj69eekq7cgd7njza&st=d0hej04r&dl=0",
  },
  {
    id: 10,
    category: "particles",
    category_id: 10,
    level: "advanced",
    is_index: false,
    answer: "おにはこわい",
    sound_resource:
      "https://dl.dropboxusercontent.com/scl/fi/ybe00sx6hc87nhycica3n/onihakowai.m4a?rlkey=hcdddo8i2mjn7cl45ptkatwgs&st=gyzsimc9&dl=0",
  },
  {
    id: 11,
    category: "particles",
    category_id: 11,
    level: "advanced",
    is_index: false,
    answer: "ろうそくをけす",
    sound_resource:
      "https://dl.dropboxusercontent.com/scl/fi/6excmxiiwdxs3ic4fwctx/rousokuwokesu.m4a?rlkey=ani6gpscx5wr8ctlpyqamd15t&st=n175os33&dl=0",
  },
  {
    id: 12,
    category: "particles",
    category_id: 12,
    level: "advanced",
    is_index: false,
    answer: "バナナはおいしい",
    sound_resource:
      "https://dl.dropboxusercontent.com/scl/fi/1f77r5cj6g4bethfmydwx/bananahaoishii.m4a?rlkey=3g5bdu36lxdc92l5tbjov8arr&st=xp6xhwev&dl=0",
  },
];
