export const DATA = [
  {
    id: 1,
    phrase_front: "あめ",
    phrase_back: "なめる",
    choices: [
      {
        id: 1,
        character: "お",
        en: "o",
        style_border: "solid 3px blue",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
      {
        id: 2,
        character: "を",
        en: "wo",
        style_border: "solid 3px red",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
    ],
    character: "wo",
    category_id: 1,
    category: "particles",
    level: "beginner",
    is_index: true,
  },
  {
    id: 2,
    phrase_front: "て",
    phrase_back: "あらう",
    choices: [
      {
        id: 1,
        character: "を",
        en: "wo",
        style_border: "solid 3px red",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 2,
        character: "お",
        en: "o",
        style_border: "solid 3px blue",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
    ],
    character: "wo",
    category_id: 2,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 3,
    phrase_front: "おばけ",
    phrase_back: "こわい",
    choices: [
      {
        id: 1,
        character: "わ",
        en: "wa",
        style_border: "solid 3px blue",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
      {
        id: 2,
        character: "は",
        en: "ha",
        style_border: "solid 3px red",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
    ],
    character: "ha",
    category_id: 3,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 4,
    phrase_front: "ばった",
    phrase_back: "むしです",
    choices: [
      {
        id: 1,
        character: "は",
        en: "ha",
        style_border: "solid 3px red",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
      {
        id: 2,
        character: "わ",
        en: "wa",
        style_border: "solid 3px blue",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
    ],
    character: "ha",
    category_id: 4,
    category: "particles",
    level: "beginner",
    is_index: false,
  },
  {
    id: 5,
    choices: [
      {
        id: 1,
        character: "を",
        en: "wo",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 2,
        character: "お",
        en: "o",
        style_height: 50,
        style_width: 50,
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
      {
        id: 3,
        character: "いもうと",
        en: "imouto",
        style_height: 200,
        style_width: 50,
        image: "https://i.ibb.co/kxKnG9P/img-imouto.jpg",
      },
      {
        id: 4,
        character: "よぶ",
        en: "yobu",
        style_height: 100,
        style_width: 50,
        image: "https://i.ibb.co/SN8pcw8/img-yobu.jpg",
      },
    ],
    character: "wo",
    category_id: 5,
    category: "particles",
    level: "intermediate",
    is_index: true,
    answer: "imouto wo yobu",
  },
];
