export const ROMAJIS_SEED_DATA = [
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: true,
    hiragana: "がっこう",
    options: [{ option: "gakkou" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "きって",
    options: [{ option: "kitte" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "せんせい",
    options: [{ option: "sennsei" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "ほうりつ ⚖️",
    options: [{ option: "houritu" }, { option: "houritsu" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "かれーらいす 🍛",
    options: [{ option: "kare-raisu" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "とうきょう",
    options: [{ option: "toukyou" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: true,
    hiragana: "えんぴつ",
    options: [{ option: "ennpitu" }, { option: "ennpitsu" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "しんぶん",
    options: [{ option: "shinnbunn" }, { option: "sinnbunn" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "けんこう 💪",
    options: [{ option: "kennkou" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "はんたい",
    options: [{ option: "hanntai" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "おんがく",
    options: [{ option: "onngaku" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "もんすたー 👾",
    options: [{ option: "monnsuta-" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: true,
    hiragana: "おきゃくさま",
    options: [{ option: "okyakusama" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "しゅくだい",
    options: [{ option: "shukudai" }, { option: "syukudai" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "じゅぎょう",
    options: [
      { option: "jugyou" },
      { option: "jyugyou" },
      { option: "zyugyou" },
    ],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "ちゃいろ",
    options: [{ option: "chairo" }, { option: "cyairo" }, { option: "tyairo" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "りょこう 🧳",
    options: [{ option: "ryokou" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: true,
    hiragana: "じどうしゃ",
    options: [
      { option: "jidousha" },
      { option: "jidousya" },
      { option: "zidousya" }, 
    ],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "でんしゃ",
    options: [{ option: "dennsha" }, { option: "dennsya" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "びょういん",
    options: [{ option: "byouinn" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "げんき 😄",
    options: [{ option: "gennki" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "じゅーす 🥤",
    options: [{ option: "ju-su" }, { option: "jyu-su" }, { option: "zyu-su" }],
  },
];
