export const ROMAJIS_SEED_DATA = [
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: true,
    hiragana: "がっこう",
    options: [{ option: "gakkou" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "きって",
    options: [{ option: "kitte" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "せんせい",
    options: [{ option: "sensei" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "ほうりつ",
    options: [{ option: "houritu" }, { option: "houritsu" }],
  },
  {
    category: "romajis",
    group: "sokuon_chouon_seion",
    groupExp: "いっぱんてきなことば",
    isIndex: false,
    hiragana: "とうきょう",
    options: [{ option: "toukyou" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: true,
    hiragana: "えんぴつ",
    options: [{ option: "enpitu" }, { option: "enpitsu" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "しんぶん",
    options: [{ option: "shinbun" }, { option: "sinbun" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "けんこう",
    options: [{ option: "kenkou" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "はんたい",
    options: [{ option: "hantai" }],
  },
  {
    category: "romajis",
    group: "hatsuon",
    groupExp: "「ん」をふくむことば",
    isIndex: false,
    hiragana: "おんがく",
    options: [{ option: "ongaku" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: true,
    hiragana: "おきゃくさま",
    options: [{ option: "okyakusama" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "しゅくだい",
    options: [{ option: "shukudai" }, { option: "syukudai" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "じゅぎょう",
    options: [
      { option: "jugyou" },
      { option: "jyugyou" },
      { option: "zyugyou" },
    ],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "ちゃいろ",
    options: [{ option: "chairo" }, { option: "cyairo" }, { option: "tyairo" }],
  },
  {
    category: "romajis",
    group: "youon",
    groupExp: "「ゃ、ゅ、ょ」をふくむことば",
    isIndex: false,
    hiragana: "りょこう",
    options: [{ option: "ryokou" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: true,
    hiragana: "じどうしゃ",
    options: [
      { option: "jidousha" },
      { option: "jidousya" },
      { option: "zidousya" },
    ],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "でんしゃ",
    options: [{ option: "densha" }, { option: "densya" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "びょういん",
    options: [{ option: "byouin" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "げんき",
    options: [{ option: "genki" }],
  },
  {
    category: "romajis",
    group: "dakuon",
    groupExp: "にごる発音をふくむことば",
    isIndex: false,
    hiragana: "ぴあの",
    options: [{ option: "piano" }],
  },
];
