export const DATA = [
  {
    id: 1,
    phrase_front: "あめ",
    phrase_back: "なめる",
    choices: [
      {
        id: 1,
        character: "お",
        pron: "o",
        props: "solid 3px blue",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
      {
        id: 2,
        character: "を",
        pron: "wo",
        props: "solid 3px red",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
    ],
    character: "wo",
    category: "particles",
    subcategory: "beginners",
    sub_id: 1,
  },
  {
    id: 2,
    phrase_front: "て",
    phrase_back: "あらう",
    choices: [
      {
        id: 1,
        character: "を",
        pron: "wo",
        props: "solid 3px red",
        image: "https://i.ibb.co/Gnyk250/img-wo.png",
      },
      {
        id: 2,
        character: "お",
        pron: "o",
        props: "solid 3px blue",
        image: "https://i.ibb.co/3TjcvyJ/img-o.png",
      },
    ],
    character: "wo",
    category: "particles",
    subcategory: "beginners",
    sub_id: 2,
  },
  {
    id: 3,
    phrase_front: "おばけ",
    phrase_back: "こわい",
    choices: [
      {
        id: 1,
        character: "わ",
        pron: "wa",
        props: "solid 3px blue",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
      {
        id: 2,
        character: "は",
        pron: "ha",
        props: "solid 3px red",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
    ],
    character: "ha",
    category: "particles",
    subcategory: "beginners",
    sub_id: 1,
  },
  {
    id: 4,
    phrase_front: "ばった",
    phrase_back: "むしです",
    choices: [
      {
        id: 1,
        character: "は",
        pron: "ha",
        props: "solid 3px red",
        image: "https://i.ibb.co/zf7Qssr/img-ha.png",
      },
      {
        id: 2,
        character: "わ",
        pron: "wa",
        props: "solid 3px blue",
        image: "https://i.ibb.co/Yj23XWD/img-wa.png",
      },
    ],
    character: "ha",
    category: "particles",
    subcategory: "beginners",
    sub_id: 2,
  },
];
